project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  title: "moniqueallyson.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    pagelayout: full

