project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  title: "Monique Allyson Hernandez"
  favicon: /image/Monique.png
  navbar:
    pinned: true
    logo: /image/Monique.png
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: Projects.qmd
        text: Projects



format:
  html:
    theme:
      light: pulse
      dark: vapor
    mainfont: quicksand
    css: styles.css
    toc: true
    pagelayout: full

