project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  title: "moniqueallyson.github.io"
  navbar:
    left:
      - href: "index.qmd"
        text: Home
      - href: "about.qmd"
        text: About Me
      - href: "Projects.qmd"
        text: Projects
      - href: "Personal Work.qmd"
        text: Personal Work
      - href: "exp.qmd"
        text: Experience
      - href: "resume.qmd"
        text: Resume


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    pagelayout: full

