project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:  
  navbar:
    pinned: true
    left:
      - href: "index.qmd"
        text: Home
      - href: "Projects.qmd"
        text: Projects
      - href: "Personal Work.qmd"
        text: Personal Work
      - href: "exp.qmd"
        text: Experience


format:
  html:
    theme: minty
    mainfont: quicksand
    css: styles.css
    toc: true
    pagelayout: full

