project:
  type: website
  output-dir: html
  resources:
    - .nojekyll

website:
  title: "Monique Allyson Hernandez"
  navbar:
    pinned: true
    left:
      - href: index.qmd
        text: Home
      - href: Projects.qmd
        text: Projects
      - href: Personal Work.qmd
        text: Poetry
      - href: exp.qmd
        text: Experience



format:
  html:
    theme: minty
    mainfont: quicksand
    css: styles.css
    toc: true
    pagelayout: full

