project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  title: "Monique Allyson Hernandez"
  favicon: /image/Monique.png
  navbar:
    pinned: true
    logo: /image/Monique.png
    left:
      - href: index.qmd
        text: Home
        href: about.qmd
        text: About Me
      - href: Projects.qmd
        text: Projects
      - href: Personal Work.qmd
        text: Poetry
      - href: exp.qmd
        text: Experience



format:
  html:
    theme: minty
    mainfont: quicksand
    css: styles.css
    toc: true
    pagelayout: full

